# Generated by Django 5.2.11 on 2026-02-21 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_remove_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
